//! Auto-generated libmpv FFI bindings.
//!
//! Generated by `build.rs` from `mpv/client.h` (system pkg-config or
//! `third_party/mpv/include` vendored fallback). See `build.rs` for the
//! allowlist and configuration.

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// Hand-written replacements for types bindgen 0.71 emits as opaque stubs
// (see build.rs). Layout matches `third_party/mpv/include/mpv/client.h`
// lines 803-845.

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mpv_node_list {
    pub num: ::std::os::raw::c_int,
    pub values: *mut mpv_node,
    pub keys: *mut *mut ::std::os::raw::c_char,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mpv_byte_array {
    pub data: *mut ::std::os::raw::c_void,
    pub size: usize,
}
