[package]
name = "jfn-input"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
name = "jfn_input"
path = "src/lib.rs"

[dependencies]
jfn-platform-abi = { path = "../platform_abi" }
jfn-playback = { path = "../playback" }
parking_lot.workspace = true

[lints]
workspace = true
