name: Sync Fork

on:
  schedule:
    - cron: '* */4 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync with upstream
        uses: XueMoMo/Sync-Fork-action@v1.0.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_repository: Vendicated/Vencord
          upstream_branch: main
          target_branch: main
          git_fetch_args: --recurse-submodules
          git_checkout_args: --recurse-submodules
          git_pull_args: --recurse-submodules
